name: 'Bastion Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-init-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: dev

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: dev

    - name: Terraform Plan
      run: terraform plan 
      working-directory: dev

  tfsec-scan:
    name: 'Terraform Security Scan (tfsec)'
    runs-on: ubuntu-latest
    needs: terraform-init-plan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup tfsec
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Run tfsec
      run: tfsec dev

  

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: tfsec-scan
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: dev

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: dev
